# Project: restaurant
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = Build/main.o Build/menu.o Build/order.o Build/payment.o
LINKOBJ  = Build/main.o Build/menu.o Build/order.o Build/payment.o
LIBS     = -L"C:/Programs/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Programs/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Programs/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Programs/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Programs/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Programs/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Programs/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Programs/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Programs/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = Build/restaurant.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
DEL      = C:\Programs\Embarcadero\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Build/main.o: main.cpp
	$(CPP) -c main.cpp -o Build/main.o $(CXXFLAGS)

Build/menu.o: menu.cpp
	$(CPP) -c menu.cpp -o Build/menu.o $(CXXFLAGS)

Build/order.o: order.cpp
	$(CPP) -c order.cpp -o Build/order.o $(CXXFLAGS)

Build/payment.o: payment.cpp
	$(CPP) -c payment.cpp -o Build/payment.o $(CXXFLAGS)
